### PR TITLE
Add .gitattributes file to enforce LF line-endings in xml

### PR DESCRIPTION
**Pull request by tsg21**
... so that tests always pass.

### CODE REVIEW

**Comment by tsg21** [comment]
Trial fix #27 

@badgerwithagun - can you see whether this resolves the issue for you? (it doesn't happen for me locally)

**Comment by badgerwithagun** [comment]
Needs testing on both Win & *Nix

**Comment by tsg21** [comment]
> Needs testing on both Win & *Nix

Not totally convinced it does. It always worked for me and @venushka locally. It just needs to work for you, @badgerwithagun

**Comment by badgerwithagun** [comment]
I don't have this issue anymore since I fixed my local settings. I'm inclined to leave it and just close the issue.  What do you think, guys?

**Comment by tsg21** [comment]
Well, if we don't include this file then some poor engineer with (legitimately) the same settings as you is going to checkout Morf and not be able to run the tests.

I think we should include it. Merge?

**Comment by badgerwithagun** [comment]
Why not. We can always change our minds later. OK, approving

**Pull request merged**
