### PR TITLE
Partial #6: Allow upgrade/deployment without Guice

### PR DESCRIPTION
**Pull request by badgerwithagun**
I'm working on the "Hello World" story.  What I want to be able to do is to deploy a database from scratch using an initial schema, then apply an upgrade.  At the moment it looks like this:

```
import static org.alfasoftware.morf.metadata.DataType.BIG_INTEGER;
import static org.alfasoftware.morf.metadata.DataType.STRING;
import static org.alfasoftware.morf.metadata.SchemaUtils.column;
import static org.alfasoftware.morf.metadata.SchemaUtils.schema;
import static org.alfasoftware.morf.metadata.SchemaUtils.table;
import static org.alfasoftware.morf.metadata.SchemaUtils.view;
import static org.alfasoftware.morf.sql.SqlUtils.field;
import static org.alfasoftware.morf.sql.SqlUtils.insert;
import static org.alfasoftware.morf.sql.SqlUtils.select;
import static org.alfasoftware.morf.sql.SqlUtils.tableRef;
import static org.alfasoftware.morf.upgrade.db.DatabaseUpgradeTableContribution.deployedViewsTable;
import static org.alfasoftware.morf.upgrade.db.DatabaseUpgradeTableContribution.upgradeAuditTable;

import java.sql.SQLException;
import java.util.Collection;
import java.util.HashSet;

import org.alfasoftware.morf.diagnostics.H2DatabaseInspector;
import org.alfasoftware.morf.jdbc.ConnectionResourcesBean;
import org.alfasoftware.morf.metadata.Schema;
import org.alfasoftware.morf.upgrade.DataEditor;
import org.alfasoftware.morf.upgrade.Deployment;
import org.alfasoftware.morf.upgrade.SchemaEditor;
import org.alfasoftware.morf.upgrade.Sequence;
import org.alfasoftware.morf.upgrade.UUID;
import org.alfasoftware.morf.upgrade.Upgrade;
import org.alfasoftware.morf.upgrade.UpgradeStep;
import org.alfasoftware.morf.upgrade.Version;

public class MorfDeploy {

  public static void main(String[] args) throws SQLException {

    // Define the target database schema (baseline)
    Schema targetSchema = schema(
      deployedViewsTable(),
      upgradeAuditTable(),
      table("Test1").columns(
        column("id", BIG_INTEGER).autoNumbered(1),
        column("val", STRING, 100)
      ),
      table("Test2").columns(
        column("id", BIG_INTEGER).autoNumbered(1),
        column("val", STRING, 100)
      )
    );

    // Any upgrade steps which lead to the baseline.  These will be
    // assumed to have already run.
    Collection<Class<? extends UpgradeStep>> upgradeSteps = new HashSet<>();
    upgradeSteps.add(CreateTest1.class);
    upgradeSteps.add(CreateTest2.class);

    // And the database
    ConnectionResourcesBean connectionResources = new ConnectionResourcesBean();
    connectionResources.setDatabaseType("H2");
    connectionResources.setHostName("localhost");
    connectionResources.setDatabaseName("test");
    connectionResources.setUserName("test");
    connectionResources.setPassword("test");

    // Deploy the schema
    Deployment.deploySchema(targetSchema, upgradeSteps, connectionResources);

    // Open the H2 database inspector so you can play with the database
    new H2DatabaseInspector(connectionResources).inspect();

    // Now let's extend the schema, with an extra table and a view
    targetSchema = schema(
      targetSchema,
      schema(
        table("Test3").columns(
          column("id", BIG_INTEGER).autoNumbered(1),
          column("val", STRING, 100)
        )
      ),
      schema(
        view("Test3View", select().from("Test3"))
      )
    );

    // Add the upgrade to create it
    upgradeSteps.add(CreateTest3.class);

    // Run the upgrade
    new SqlScriptExecutorProvider(connectionResources).get().execute(Upgrade.createPath(targetSchema, upgradeSteps, connectionResources).getSql());

    // Open the H2 database inspector so you can play with the database
    new H2DatabaseInspector(connectionResources).inspect();
  }


  @Sequence(1496853575)
  @UUID("e3667c15-74b5-4bed-b87f-36a5f686e8db")
  @Version("0.0.1")
  public static final class CreateTest1 implements UpgradeStep {

    @Override
    public String getJiraId() {
      return "FOO-1";
    }

    @Override
    public String getDescription() {
      return "Create table Test1";
    }

    @Override
    public void execute(SchemaEditor schema, DataEditor data) {
      schema.addTable(
        table("Test1").columns(
          column("id", BIG_INTEGER).autoNumbered(1),
          column("val", STRING, 100)
        )
      );
    }
  }


  @Sequence(1496853658)
  @UUID("94a97d5a-2ac6-46fd-9249-dc61b1b8c90a")
  @Version("0.0.1")
  public static final class CreateTest2 implements UpgradeStep {

    @Override
    public String getJiraId() {
      return "FOO-1";
    }

    @Override
    public String getDescription() {
      return "Create table Test2";
    }

    @Override
    public void execute(SchemaEditor schema, DataEditor data) {
      schema.addTable(
        table("Test2").columns(
          column("id", BIG_INTEGER).autoNumbered(1),
          column("val", STRING, 100)
        )
      );
    }
  }


  @Sequence(1496853841)
  @UUID("d962f6d0-6bfe-4c9f-847b-6319ad99ba54")
  @Version("0.0.1")
  public static final class CreateTest3 implements UpgradeStep {

    @Override
    public String getJiraId() {
      return "FOO-1";
    }

    @Override
    public String getDescription() {
      return "Create table Test3";
    }

    @Override
    public void execute(SchemaEditor schema, DataEditor data) {
      schema.addTable(
        table("Test3").columns(
          column("id", BIG_INTEGER).autoNumbered(1),
          column("val", STRING, 100)
        )
      );
      data.executeStatement(
        insert()
        .into(tableRef("Test3"))
        .from(
          select(
            field("id"),
            field("val"))
          .from("Test1")
        )
      );
    }
  }
}
```

This is definitely just a first draft.  The new static methods I've created here could probably have a nicer-looking signature (possibly a builder?) and the use of `SqlScriptExecutor` here is pretty ugly too:

`new SqlScriptExecutorProvider(connectionResources).get().execute(Upgrade.createPath(targetSchema, upgradeSteps, connectionResources).getSql());`

But it's a start.  Comments welcome.

### CODE REVIEW

**Comment by badgerwithagun** [comment]
Main other issues outstanding to resolve #6, I think, are:

* Jira ID should be removed from Morf's `UpgradeStep` interface
* Lack of functional consistency in where annotations or methods are used on `UpgradeStep`
* Imbalance in the way `Deployment` works (just does it) versus `Upgrade` (creates a script which you have to run with `SqlScriptExecutor`)

**Comment by tsg21** [comment]
I'm ok with this. There's some fairly improvements we could make to the API, given that example, but this is a good start.

**Comment by badgerwithagun** [comment]
OK, let's put this in for now, and and I can get the documentation updated.

**Comment by badgerwithagun** [comment]
Merged to Alfa's internal fork for QA checks.

If approved, I'll merge this PR.

**Pull request merged**
