### PR TITLE
Reducing console output during build

### PR DESCRIPTION
**Pull request by venushka**
Fix for #38

Also removed sudo flag from travis build configuration as it pins the builds to out-dated version of linux that travis are phasing out.

### CODE REVIEW

**Comment by venushka** [comment]
Already useful, there are some JavaDoc warnings in the nuodb module.

`
[WARNING] Javadoc Warnings
[WARNING] Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
[WARNING] /home/travis/build/alfasoftware/morf/morf-nuodb/src/main/java/org/alfasoftware/morf/jdbc/nuodb/NuoDBHelper.java:22: warning: no @param for stringOfDouble
[WARNING] public static Double nuoDBConvertStringToDouble(String stringOfDouble) {
[WARNING] ^
[WARNING] /home/travis/build/alfasoftware/morf/morf-nuodb/src/main/java/org/alfasoftware/morf/jdbc/nuodb/NuoDBHelper.java:22: warning: no @return
[WARNING] public static Double nuoDBConvertStringToDouble(String stringOfDouble) {
[WARNING] ^
[WARNING] /home/travis/build/alfasoftware/morf/morf-nuodb/src/main/java/org/alfasoftware/morf/jdbc/nuodb/NuoDBHelper.java:33: warning: no @param for referenceToCast
[WARNING] public static Cast nuoDBCastToString(AliasedField referenceToCast, int length) {
[WARNING] ^
[WARNING] /home/travis/build/alfasoftware/morf/morf-nuodb/src/main/java/org/alfasoftware/morf/jdbc/nuodb/NuoDBHelper.java:33: warning: no @param for length
[WARNING] public static Cast nuoDBCastToString(AliasedField referenceToCast, int length) {
[WARNING] ^
[WARNING] /home/travis/build/alfasoftware/morf/morf-nuodb/src/main/java/org/alfasoftware/morf/jdbc/nuodb/NuoDBHelper.java:33: warning: no @return
[WARNING] public static Cast nuoDBCastToString(AliasedField referenceToCast, int length) {
[WARNING] ^
[WARNING] /home/travis/build/alfasoftware/morf/morf-nuodb/src/main/java/org/alfasoftware/morf/jdbc/nuodb/NuoDBHelper.java:43: warning: no @param for bigDecimal
[WARNING] public static String nuoDBConvertBigDecimalToPlainString(BigDecimal bigDecimal) {
[WARNING] ^
[WARNING] /home/travis/build/alfasoftware/morf/morf-nuodb/src/main/java/org/alfasoftware/morf/jdbc/nuodb/NuoDBHelper.java:43: warning: no @return
[WARNING] public static String nuoDBConvertBigDecimalToPlainString(BigDecimal bigDecimal) {
[WARNING] ^
`

**Comment by badgerwithagun** [comment]
My thinking is that the wish to suppress tests logging is a very Travis-specific issue which shouldn't affect tests run in an IDE, local builds or Alfa's internal CI where having everything in the build log is usually more convenient than scrabbling around downloading build artifacts.

Could we perhaps try and delete all these log config files in the main code but just drop them in during Travis builds?

**Comment by venushka** [comment]
> My thinking is that the wish to suppress tests logging is a very Travis-specific issue which shouldn't affect tests run in an IDE, local builds or Alfa's internal CI where having everything in the build log is usually more convenient than scrabbling around downloading build artifacts.

Its a Maven build specific issue in my opinion as the excessive amount of logs printed in the middle of the build log make is very difficult to spot any warnings in the build such as character encoding warning, javadoc warnings, deprecation warnings, etc. We are already doing this for Alfa internal builds when running with jacoco runner, so this is not any different actually.

> Could we perhaps try and delete all these log config files in the main code but just drop them in during Travis builds?

Good point! Got me thinking of finding a way to use a different log4j configuration when running the Maven build, and did indeed find a way. I've changed all the log4j configuration files in test resources to log to console (previously some of them were writing to files and some to console) and added system property to the surefire plugin to use a different log4j configuration file when running the build in `coverage-per-test` profile, which we only use in CI running with coverage. This would make the logs show in the console when running tests in the IDE and local builds. I think this way the CI will let us know when the test fails and optionally collect junit logs artifacts for investigation and also local builds will remain unchanged.

This pull request now include all the changes.

**Comment by badgerwithagun** [comment]
I'm still not convinced by the idea of shipping Morf with log4j config files included at all - feels like log configuration should be the responsibility of the application (related to #9), not of Morf itself.

This is much better than what we have now though.  Tempted to say let's get this in for now and agonise over the rights and wrongs of our logging setup separately.

**Comment by venushka** [comment]
Actually all the log config fields are in test resources directory, so we are really not shipping them. They are only used for testing. Haven’t checked but I think we only depend on log4j library in test scope as well.

**Comment by badgerwithagun** [comment]
It is in test scope, you're right! OK, great, I'm going to approve this.

**Pull request merged**
